CREATE TABLE IF NOT EXISTS TB_USERS (
    US_ID BIGSERIAL PRIMARY KEY NOT NULL,
    US_FIRST_NAME VARCHAR(100) NOT NULL,
    US_LAST_NAME VARCHAR(100) NOT NULL,
    US_EMAIL VARCHAR(255) UNIQUE NOT NULL,
    US_PASSWORD VARCHAR(255) NOT NULL,
    US_PROFILE_PICTURE VARCHAR DEFAULT NULL,
    US_CREATED_AT TIMESTAMP NOT NULL,
    US_UPDATED_AT TIMESTAMP NOT NULL,
    US_DISABLED_AT TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS TB_ROLES (
    RL_ID BIGSERIAL PRIMARY KEY NOT NULL,
    RL_NAME TEXT CHECK (RL_NAME IN ('ADMIN', 'USER')) NOT NULL DEFAULT 'USER',
    RL_CREATED_AT TIMESTAMP NOT NULL,
    RL_UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_USERS_ROLES (
    UR_USER_ID BIGSERIAL REFERENCES TB_USERS(US_ID) ON DELETE SET NULL,
    UR_ROLE_ID BIGSERIAL REFERENCES TB_ROLES(RL_ID) ON DELETE SET NULL,
    UR_CREATED_AT TIMESTAMP NOT NULL,
    UR_UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_MOVIES (
    MO_ID BIGSERIAL PRIMARY KEY NOT NULL,
    MO_TITLE VARCHAR(100) NOT NULL UNIQUE,
    MO_DESCRIPTION VARCHAR(255),
    MO_POSTER_IMAGE VARCHAR(255),
    MO_TRAILER_VIDEO_URL VARCHAR(300),
    MO_DURATION_SECONDS BIGINT NOT NULL,
    MO_RELEASE_DATE TIMESTAMP,
    MO_STUDIO_NAME VARCHAR(100),
    MO_CAST VARCHAR(500),
    MO_CREATED_AT TIMESTAMP NOT NULL,
    MO_UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_SESSIONS (
    SS_ID BIGSERIAL PRIMARY KEY NOT NULL,
    SS_START TIMESTAMP NOT NULL,
    SS_END TIMESTAMP NOT NULL,
    SS_CREATED_AT TIMESTAMP NOT NULL,
    SS_UPDATED_AT TIMESTAMP NOT NULL,
    SS_MOVIE_ID BIGSERIAL REFERENCES TB_MOVIES(MO_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS TB_SEATS (
    ST_ID BIGSERIAL PRIMARY KEY NOT NULL,
    ST_ROW TEXT CHECK (ST_ROW IN ('A', 'B', 'C', 'D', 'E', 'F', 'G')) NOT NULL,
    ST_NUMBER INTEGER NOT NULL,
    ST_ACESSIBILITY BOOLEAN NOT NULL,
    ST_CREATED_AT TIMESTAMP NOT NULL,
    ST_UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_ROOMS (
    RO_ID BIGSERIAL PRIMARY KEY NOT NULL,
    RO_NUMBER VARCHAR(10) NOT NULL UNIQUE,
    RO_CREATED_AT TIMESTAMP NOT NULL,
    RO_UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_ROOMS_SESSIONS (
    RS_CREATED_AT TIMESTAMP NOT NULL,
    RS_UPDATED_AT TIMESTAMP NOT NULL,
    RS_SESSION_ID BIGSERIAL REFERENCES TB_SESSIONS(SS_ID) ON DELETE SET NULL,
    RS_ROOM_ID BIGSERIAL REFERENCES TB_ROOMS(RO_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS TB_ROOMS_SEATS (
    RST_CREATED_AT TIMESTAMP NOT NULL,
    RST_UPDATED_AT TIMESTAMP NOT NULL,
    RST_ROOM_ID BIGSERIAL REFERENCES TB_ROOMS(RO_ID) ON DELETE SET NULL,
    RST_SEAT_ID BIGSERIAL REFERENCES TB_SEATS(ST_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS TB_RESERVATIONS (
    RES_ID BIGSERIAL PRIMARY KEY NOT NULL,
    RES_CREATED_AT TIMESTAMP NOT NULL,
    RES_UPDATED_AT TIMESTAMP NOT NULL,
    RES_USER_ID BIGSERIAL REFERENCES TB_USERS(US_ID) ON DELETE SET NULL,
    RES_SESSION_ID BIGSERIAL REFERENCES TB_SESSIONS(SS_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS TB_RESERVATIONS_ROOM_SEAT (
    RRS_CREATED_AT TIMESTAMP NOT NULL,
    RRS_UPDATED_AT TIMESTAMP NOT NULL,
    RRS_RESERVATION_ID BIGSERIAL REFERENCES TB_RESERVATIONS(RES_ID) ON DELETE SET NULL,
    RRS_ROOM_ID BIGSERIAL REFERENCES TB_ROOMS(RO_ID) ON DELETE SET NULL,
    RRS_SEAT_ID BIGSERIAL REFERENCES TB_SEATS(ST_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS TB_MOVIE_TICKETS (
    MVT_ID BIGSERIAL PRIMARY KEY NOT NULL,
    MVT_NORMAL_PRICE NUMERIC(38, 2) NOT NULL,
    MVT_STUDENT_PRICE NUMERIC(38, 2) NOT NULL,
    MVT_SPECIAL_PRICE NUMERIC(38, 2) NOT NULL,
    MVT_IS_FREE BOOLEAN NOT NULL DEFAULT FALSE,
    MVT_CREATED_AT TIMESTAMP NOT NULL,
    MVT_UPDATED_AT TIMESTAMP NOT NULL,
    MVT_MOVIE_ID BIGSERIAL REFERENCES TB_MOVIES(MO_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS TB_RESERVATIONS_MOVIES_TICKETS (
    RMT_PRICE_PAID NUMERIC(38, 2) NOT NULL,
    RMT_TYPE TEXT CHECK (RMT_TYPE IN ('NORMAL', 'SPECIAL', 'STUDENT')),
    RMT_CREATED_AT TIMESTAMP NOT NULL,
    RMT_UPDATED_AT TIMESTAMP NOT NULL,
    RMT_RESERVATION_ID BIGSERIAL REFERENCES TB_RESERVATIONS(RES_ID) ON DELETE SET NULL,
    RMT_MOVIE_TICKET_ID BIGSERIAL REFERENCES TB_MOVIE_TICKETS(MVT_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS TB_GENRES (
    GR_ID BIGSERIAL PRIMARY KEY NOT NULL,
    GR_NAME VARCHAR(50) NOT NULL UNIQUE,
    GR_CREATED_AT TIMESTAMP NOT NULL,
    GR_UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_MOVIES_GENRES (
    MG_CREATED_AT TIMESTAMP NOT NULL,
    MG_UPDATED_AT TIMESTAMP NOT NULL,
    MG_MOVIE_ID BIGSERIAL REFERENCES TB_MOVIES(MO_ID) ON DELETE SET NULL,
    MG_GENRE_ID BIGSERIAL REFERENCES TB_GENRES(GR_ID) ON DELETE SET NULL
);