INSERT INTO tb_rooms (RO_ID, RO_NUMBER, RO_CREATED_AT, RO_UPDATED_AT)
VALUES (DEFAULT, 1, now(), now()) ON CONFLICT DO NOTHING;

INSERT INTO tb_rooms (RO_ID, RO_NUMBER, RO_CREATED_AT, RO_UPDATED_AT)
VALUES (DEFAULT, 2, now(), now()) ON CONFLICT DO NOTHING;

INSERT INTO tb_rooms (RO_ID, RO_NUMBER, RO_CREATED_AT, RO_UPDATED_AT)
VALUES (DEFAULT, 3, now(), now()) ON CONFLICT DO NOTHING;

INSERT INTO tb_rooms (RO_ID, RO_NUMBER, RO_CREATED_AT, RO_UPDATED_AT)
VALUES (DEFAULT, 4, now(), now()) ON CONFLICT DO NOTHING;

INSERT INTO tb_rooms (RO_ID, RO_NUMBER, RO_CREATED_AT, RO_UPDATED_AT)
VALUES (DEFAULT, 5, now(), now()) ON CONFLICT DO NOTHING;