/* A SEATS */
INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'A', 1, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'A', 2, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'A', 3, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'A', 4, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'A', 5, true, NOW(), NOW());

/* B SEATS */
INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'B', 1, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'B', 2, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'B', 3, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'B', 4, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'B', 5, true, NOW(), NOW());

/* C SEATS */
INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'C', 1, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'C', 2, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'C', 3, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'C', 4, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'C', 5, true, NOW(), NOW());

/* D SEATS */
INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'D', 1, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'D', 2, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'D', 3, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'D', 4, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'D', 5, true, NOW(), NOW());

/* E SEATS */
INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'E', 1, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'E', 2, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'E', 3, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'E', 4, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'E', 5, true, NOW(), NOW());

/* F SEATS */
INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'F', 1, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'F', 2, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'F', 3, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'F', 4, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'F', 5, false, NOW(), NOW());

/* G SEATS */
INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'G', 1, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'G', 2, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'G', 3, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'G', 4, false, NOW(), NOW());

INSERT INTO tb_seats (ST_ID, ST_ROW, ST_NUMBER, ST_ACESSIBILITY, ST_CREATED_AT, ST_UPDATED_AT)
VALUES (DEFAULT, 'G', 5, false, NOW(), NOW());