/* ROOM 1 */
INSERT INTO tb_rooms_seats (RST_CREATED_AT, RST_UPDATED_AT, RST_ROOM_ID, RST_SEAT_ID)
VALUES  (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '1'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 5));

/* ROOM 2 */
INSERT INTO tb_rooms_seats (RST_CREATED_AT, RST_UPDATED_AT, RST_ROOM_ID, RST_SEAT_ID)
VALUES  (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '2'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 5));

/* ROOM 3 */
INSERT INTO tb_rooms_seats (RST_CREATED_AT, RST_UPDATED_AT, RST_ROOM_ID, RST_SEAT_ID)
VALUES  (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '3'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 5));

/* ROOM 4 */
INSERT INTO tb_rooms_seats (RST_CREATED_AT, RST_UPDATED_AT, RST_ROOM_ID, RST_SEAT_ID)
VALUES  (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '4'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 5));

/* ROOM 5 */
INSERT INTO tb_rooms_seats (RST_CREATED_AT, RST_UPDATED_AT, RST_ROOM_ID, RST_SEAT_ID)
VALUES  (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'A' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'B' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'C' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'D' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'E' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'F' AND st_number = 5)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 1)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 2)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 3)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 4)),
        (now(), now(), (SELECT ro_id FROM tb_rooms WHERE ro_number = '5'), (SELECT st_id FROM tb_seats WHERE st_row = 'G' AND st_number = 5));