version: "3"

services:
  database:
    container_name: "reservation-app"
    image: "bitnami/postgresql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reservation-app
  cache:
    container_name: "redis-reservation-app"
    image: redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"