server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: reservation-app
  liquibase:
    change-log: classpath:db/changelog/master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation-app
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    root: WARN
    org:
      springframework:
        web: info
        boot:
          autoconfigure:
            security:
              servlet:
                UserDetailsServiceAutoConfiguration: off
      hibernate: ERROR

jwt:
  priv-rsa: ${PRIVATE_KEY}
  pub-rsa: ${PUBLIC_KEY}
  issuer: "reservation-app"

cache:
  redis:
    host: localhost
    port: 6379
    password: redis
